# mybatis-plus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8201
spring:
  application:
    name: service-hosp
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  data:
#    mongodb:
#      database: yygh_hosp
#      host: 192.168.187.100
#      port: 27017
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.142.207:3306/yygh?characterEncoding=utf-8&useSSL=false
    username: root
    password: 20040816Ywj
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  profiles:
#    active: dev
#  rabbitmq:
#    host: 192.168.187.100
#    password: guest
#    port: 5672
#    username: guest
logging:
  config: classpath:logback-spring.xml
